### ISSUE TITLE
RSS vs REST API?

### ISSUE THREAD

**Issue by oguruma1218** [ChrisRAoW/mautic-rss-to-email-bundle#56] opened 2022-01-05 03:55 UTC
I'm a coding and Mautic noobie, so please forgive me, but why not just use the Wordpress REST API to get the posts instead of an RSS feed? 

As I understand it, the API will give you completely granular control over which posts, and which post meta you pluck out. 

For example, one user commented in a different issue about wanting to pull out custom fields.

**Comment by ChrisRAoW** [comment] 2022-01-05 08:39
Duplicate of https://github.com/ChrisRAoW/mautic-rss-to-email-bundle/issues/55. Will close this one.

**Closed by ChrisRAoW** 2022-01-05 08:39 UTC
